name: Build macOS Artifact

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'src-tauri/**'
      - '.github/workflows/build-macos.yml'

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test
      
      - name: Set up Rust
        run: |
          rustup target add x86_64-apple-darwin

      - name: Build Tauri application
        run: npm run tauri:build:macos

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: minesweeper-macos
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/Minesweeper.app
